server:
  port: 8093

spring:
  application:
    name: msvc-notificaciones
  datasource:
    url: jdbc:mysql://localhost:3306/noti
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


  eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka